language: java
script:
- "./gradlew clean build"
jdk:
- oraclejdk8
deploy:
  provider: heroku
  app: arrowcraft-web
  api_key:
    secure: GWyT5J+1zy44GkV1Z25M85QKiR8XNUBF82IUsXA7dS3fl5fahBiJxYizXylNpr5vmxNtO9CEwoxM92XrGoNkwf1lGf8gX3bYbzFBOwZw4k9Wjo/2Et4XXBxhnwV8eKIg0NRfp+q67/0H4KWVw3BChIqsStgwM0gRwbRjxLUbPKb58gccSuMHt2jX6wpNmumNQs1e25xRK67YuOFvP5NDuD+XOnpLIduu9qywI3BE5XDnFe6tx4xQRyOIkH0BcdYspqf9BV5KW0zigGKzxfB89b+EUIBISgkJ3lbbk60U2Lhs4+yXHOxwbWa5z5xjsleIPz3+Vph7Y4PT6AN2p4YIwsPiaCJRX1zQ3zqH2efGsoRuLnyYrwACGZlKpO54v3GTmbINPUIAk2Ak0QtaVE1/7d6LlORStu+gcur2Qk03Ml0uk3D0nT0ROtI4b4/fWxrlawFwXLvbR0JSfMRXfNLJdpVkcCURYedwtsS+DPaBColETtC8zZvWKIopSZjvEwnwdVsrEwJdlOHqKsfrwz3Xj5SPA/7gxKuuqrp1u/cGBsGyZ0np8ZIUQAzsFjrS1YpYvZFeiSa0EOw9bv9CtEpyMr4cGvvl0bXyqE3fMHhuI4gJc1jC9DQET4nXg94rVE8Wpzn2sr2tkY3SeMvuztxBxq5nd5LuR4m2c+RuNLAJAPQ=
